server:
  port: 8084 # auth=8081; catalog=8080; search=8083; storage=8084; order=8085; payment=8086; library=8087; review=8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

# (tuỳ chọn) bật health/actuator về sau:
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
