server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:authdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  application:
    name: booknest-auth

jwt:
  secret: ${JWT_SECRET:ChangeThisSecretKeyChangeThisSecretKey}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

logging:
  level:
    org.hibernate.SQL: warn

