# application.yml
server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://mysql-auth:3306/xac_thuc_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: booknest-auth
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: http://localhost:8086/api/payments/vnpay_return
  tmn-code: "OMZF7JB7"
  secret-key: "J6S80U7KQ2LKSIK0Q8QJK6K8LVVGPUVD"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
